@startuml trabalho_engenharia_routes

package "Service" {
    interface IRoutes {
        - void createRoutes()
        - Object salvar(Object obj)
        - Object verificar(Object obj)
    }

    class AlunoRoutes implements IRoutes {
        - void createRoutes()
        - Object verificar(String cpf)
        - Object salvar(Object obj)
    }

    class ProfessorRoutes implements IRoutes {
        - void createRoutes()
        - Object verificar(String cpf)
        - Object salvar(Object obj)
    }

    class DisciplinaRoutes implements IRoutes {
        - void createRoutes()
        - Object verificar(String nome)
        - Object salvar(Object obj)

    }

    class CursoRoutes implements IRoutes {
        - void createRoutes()
        - Object salvar(Object obj)
        - Object verificar(String nome)
    }
}