@startuml Diagrama de Sequencia

participant Frontend as Frontend
participant "AlunoRoute(route) : IRoutes" as Routes
participant "AlunoController(alunoController) : IAlunoController" as AlunoController
participant "fone: Telefone" as Telefone
participant "TelefoneDAO(telefoneDAO) : ITelefoneDAO" as TelefoneDAO
participant "endereco: Endereco" as Endereco
participant "EnderecoDAO(enderecoDAO) : IEnderecoDAO" as EnderecoDAO
participant "aluno: Aluno" as Aluno
participant "AlunoDAO(alunoDAO) : IAlunoDAO" as AlunoDAO

autonumber 1.1
' Buscar aluno
Frontend->Routes: res = get("api/aluno/{id}", req): Aluno
Routes->AlunoController: res = buscar(req.body.id): Aluno
AlunoController->AlunoDAO: res = buscar(id): Aluno
AlunoDAO->AlunoController: res
AlunoController->Routes: res
Routes->Frontend: res

' Buscar todos alunos
autonumber inc A
Frontend->Routes: res = get("api/aluno", req): List<Aluno>
Routes->AlunoController: res = buscarTodos(): List<Aluno>
AlunoController->AlunoDAO: res = buscarTodos(): List<Aluno>
AlunoDAO->AlunoController: res
AlunoController->Routes: res
Routes->Frontend: res

' Buscar aluno por cpf
autonumber inc A
Frontend->Routes: res = get("api/aluno/cpf/{cpf}", req): Aluno
Routes->AlunoController: res = buscarPorCpf(req.body.cpf): Aluno
AlunoController->AlunoDAO: res = buscarPorCpf(cpf): Aluno
AlunoDAO->AlunoController: res
AlunoController->Routes: res
Routes->Frontend: res
