@startuml Diagrama de Sequencia

participant Frontend as Frontend
participant "ProfessorRoute(route) : IRoutes" as Routes
participant "ProfessorController(professorController) : IProfessorController" as ProfessorController
participant "fone: Telefone" as Telefone
participant "TelefoneDAO(telefoneDAO) : ITelefoneDAO" as TelefoneDAO
participant "endereco: Endereco" as Endereco
participant "EnderecoDAO(enderecoDAO) : IEnderecoDAO" as EnderecoDAO
participant "professor: Professor" as Professor
participant "ProfessorDAO(professorDAO) : IProfessorDAO" as ProfessorDAO

autonumber 1.1
' Buscar professor
Frontend->Routes: res = get("api/professor/{id}", req): Professor
Routes->ProfessorController: res = buscar(req.body.id): Professor
ProfessorController->ProfessorDAO: res = buscar(id): Professor
ProfessorDAO->ProfessorController: res
ProfessorController->Routes: res
Routes->Frontend: res

' Buscar todos professors
autonumber inc A
Frontend->Routes: res = get("api/professor", req): List<Professor>
Routes->ProfessorController: res = buscarTodos(): List<Professor>
ProfessorController->ProfessorDAO: res = buscarTodos(): List<Professor>
ProfessorDAO->ProfessorController: res
ProfessorController->Routes: res
Routes->Frontend: res

' Buscar professor por cpf
autonumber inc A
Frontend->Routes: res = get("api/professor/cpf/{cpf}", req): Professor
Routes->ProfessorController: res = buscarPorCpf(req.body.cpf): Professor
ProfessorController->ProfessorDAO: res = buscarPorCpf(cpf): Professor
ProfessorDAO->ProfessorController: res
ProfessorController->Routes: res
Routes->Frontend: res
