@startuml Diagrama de Sequencia

participant Frontend as Frontend
participant "CursoRoute(route) : IRoutes" as Routes
participant "CursoController(cursoController) : ICursoController" as CursoController
participant "curso: Curso" as Curso
participant "CursoDAO(cursoDAO) : ICursoDAO" as CursoDAO

autonumber 1.1
' Verificar se o curso já existe
Frontend->Routes: res = post("api/curso", req): Curso
Routes->CursoController: res = verificarCurso(req.body.nome): Curso
CursoController->CursoDAO: res = buscarCursoPorNome(nome): Curso
CursoDAO->CursoController: res
CursoController->Routes: res
Routes->Frontend: res

' Armazenar curso
Routes->CursoController: res = inserir(req.body): Mensagem
CursoController->Curso: setNomeCurso(req.nome)
CursoController->Curso: setCampus(req.campus)
CursoController->CursoDAO: res = inserir(curso): Mensagem
CursoDAO->CursoController: res
CursoController->Routes: res
Routes->Frontend: res
