@startuml Diagrama de Sequencia

participant Frontend as Frontend
participant "DisciplinaRoute(route) : IRoutes" as Routes
participant "DisciplinaController(disciplinaController) : IDisciplinaController" as DisciplinaController
participant "DisciplinaDAO(disciplinaDAO) : IDisciplinaDAO" as DisciplinaDAO
participant "disciplina: Disciplina" as Disciplina
participant "PrerequisitoRoute(route) : IRoutes" as PRoutes
participant "PrerequisitoController(prerequisitoController) : IPrerequisitoController" as PrerequisitoController
participant "PrerequisitoDAO(prerequisitoDAO) : IPrerequisitoDAO" as PrerequisitoDAO
participant "prerequisito: Prerequisito" as Prerequisito

' Atualizar prerequisitos
autonumber 1.1
Frontend->PRoutes: res = put("api/prerequisito/", req): Prerequisito
PRoutes->PrerequisitoController: res = alterar(req.body.prerequisitos): Prerequisito
PrerequisitoController->Prerequisito: setDisciplina(req.id_disciplina)
PrerequisitoController->Prerequisito: setPreRequisito(req.prerequisito)
PrerequisitoController->PrerequisitoDAO: res = alterar(prerequisito): Prerequisito
PrerequisitoDAO->PrerequisitoController: res
PrerequisitoController->PRoutes: res
PRoutes->Frontend: res

' Atualizar disciplina
autonumber inc A
Frontend->Routes: res = put("api/disciplina/", req): Disciplina
Routes -> DisciplinaController: res = alterar(req.body): Disciplina
DisciplinaController->Disciplina: setNome(req.nome)
DisciplinaController->Disciplina: setDescricao(req.descricao)
DisciplinaController->Disciplina: addPreRequisitos(req.preRequisitos)
DisciplinaController->DisciplinaDAO: res = alterar(disciplina): Disciplina
DisciplinaDAO->DisciplinaController: res
DisciplinaController->Routes: res
Routes->Frontend: res

' Remover prerequisitos
autonumber inc A
Frontend->PRoutes: res = delete("api/prerequisito/{id}", req): Prerequisito
PRoutes->PrerequisitoController: res = remover(req.body.id_prerequisito): Prerequisito
PrerequisitoController->PrerequisitoDAO: res = remover(id_prerequisito): Prerequisito
PrerequisitoDAO->PrerequisitoController: res
PrerequisitoController->PRoutes: res
PRoutes->Frontend: res

' Remover disciplina
autonumber inc A
Frontend->Routes: res = delete("api/disciplina/{id}", req): Disciplina
Routes -> DisciplinaController: res = remover(req.body.id_disciplina): Disciplina
DisciplinaController->DisciplinaDAO: res = remover(id_disciplina): Disciplina
DisciplinaDAO->DisciplinaController: res
DisciplinaController->Routes: res
Routes->Frontend: res
