@startuml trabalho_engenharia_persistence

package "persistence" {
    class Pessoa {
        - nome: String
        - sobrenome: String
        - cpf: String
        - endereco: Endereco
        - telefone: List<Telefone>
        - sexo: String
        - raca: String

        + getNome(): String
        + setNome(nome: String): boolean
        + getSobrenome(): String
        + setSobrenome(sobrenome: String): boolean
        + getCpf(): String
        + setCpf(cpf: String): boolean
        + getEndereco(): Endereco
        + setEndereco(endereco: Endereco): boolean
        + getListTelefone(): List<Telefone>
        + addTelefone(telefone: Telefone): boolean
        + getSexo(): String
        + setSexo(sexo: String): boolean
        + getRaca(): String
        + setRaca(raca: String): boolean
    }

    Pessoa <|-- Aluno
    Aluno --o Curso
    class Aluno {
        - dataIngresso: Date
        - dataNascimento: Date

        + getDataIngresso(): Date
        + setDataIngresso(data: Date): boolean
        + getDataNascimento(): Date
        + setDataNascimento(data: Date): boolean
    }

    Pessoa <|-- Professor
    Professor --o Curso
    class Professor {
        - dataContratacao: Date
        - departamento: String
        - salario: float

        + getSalario(): float
        + setSalario(salario: float): boolean
        + getDepartamento(): String
        + setDepartamento(departamento: String): boolean
        + getDataContratacao(): Date
        + setDataContratacao(data: Date): boolean
    }

    Pessoa o-- Endereco
    Curso o-- Endereco
    class Endereco {
        - logradouro: String
        - local: String
        - numero: int
        - cep: String
        - tipo: String

        + getLogradouro(): String
        + setLogradouro(logradouro: String): boolean
        + getLocal(): String
        + setLocal(local: String): boolean
        + getNumero(): int
        + setNumero(numero: int): boolean
        + getCep(): String
        + setCep(cep: String): boolean
        + getTipo(): String
        + setTipo(tipo: String): boolean
    }

    Pessoa o-- Telefone
    class Telefone {
        - cod_pais: int
        - ddd: String
        - number: String

        + getCodPais(): int
        + setCodPais(codPais: int): boolean
        + getDdd(): String
        + setDdd(ddd: String): boolean
        + getNumber(): String
        + setNumber(number: String): boolean
    }

    class Curso{
        - nome: String
        - campus: String
        - endereco: Endereco

        + getNomeCurso(): String
        + setNomeCurso(nome: String): boolean
        + getCampus(): String
        + setCampus(campus: String): boolean
        + getEndereco(): Endereco
        + setEndereco(endereco: Endereco): boolean
    }

    Disciplina --o Curso
    class Disciplina {
        - nome: String
        - descricao: String
        - preRequisitos: List < Disciplina >

        + getNome(): String
        + setNome(nome: String): boolean
        + getDescricao(): String
        + setDescricao(descricao: String): boolean
        + getListPreRequisitos(): List<Disciplina>
        + addPreRequisito(preRequisito: Disciplina): boolean
    }

    Horario o-- Periodo
    class Horario {
        - periodo: Periodo
        - dia: Date
        - horaInicial: Time
        - horaFinal: Time

        + getPeriodo(): Periodo
        + setPeriodo(periodo: Periodo): boolean
        + getDia(): Date
        + setDia(dia: Date): boolean
        + getHoraInicial(): Time
        + setHoraInicial(horaInicial: Time): boolean
        + getHoraFinal(): Time
        + setHoraFinal(horaFinal: Time): boolean
    }
    
    Sala o-- Equipamento
    class Sala {
        - predio: String
        - sala: String
        - capacidade: int
        - equipamentos: List < Equipamento >

        + getPredio(): String
        + setPredio(predio: String): boolean
        + getSala(): String
        + setSala(sala: String): boolean
        + getCapacidade(): int
        + setCapacidade(capacidade: int): boolean
        + getListEquipamentos(): List<Equipamento>
        + addEquipamento(equipamento: Equipamento): boolean
    }

    class ModeloEquipamento {
        - nome: String
        - marca String

        + getNome(): String
        + setNome(nome: String): boolean
        + getMarca(): String
        + setMarca(marca: String): boolean
    }

    ModeloEquipamento <|-- Equipamento
    class Equipamento {
        - estado: enum
        - data_aquisicao: Date

        + getEstado(): enum
        + setEstado(estado: enum): boolean
        + getDataAquisicao(): Date
        + setDataAquisicao(data: Date): boolean
    }
}

@enduml
