@startuml

package "persistence" {

    class Pessoa {
        - idPessoa: int
        - nome: String
        - sobrenome: String
        - cpf: String
        - endereco: Endereco
        - telefone: Telefone
        - sexo: String
        - raca: String
    }

    Pessoa <|-- Aluno
    class Aluno {
        - idCurso: int
        - dataIngresso: Date

    }

    Pessoa <|-- Professor
    class Professor {
        - dataContratacao: Date
        - departamento: String
        - salario: float
        - idCurso: int

        - getIdCurso(): int
        - setIdCurso(id: int): boolean
        - getSalario(): float
        - setSalario(salario: float): boolean
        - getDepartamento(): String
        - setDepartamento(departamento: String): boolean
        - getDataContratacao(): Date
        - setDataContratacao(data: Date): boolean
    }

    class Endereco {
        - idEndereco: int
        - logradouro: String
        - local: String
        - numero: int
        - cep: String
        - tipo: String
    }

    class Telefone {
        - idTelefone: int
        - idPessoa: int
        - cod_pais: int
        - ddd: String
        - numTelefone
    }

    class Disciplina {
        - idDisciplina: int
        - idCurso: int
        - nome: String
        - descricao: String
        - preRequisito: List < Disciplina >
    }

    class Horario {
        - idHorario: int
        - idPeriodo: int
        - dia: String
        - horaInicial: String
        - horaFinal: String
    }

    class Sala {
        - idSala: int
        - predio: String
        - sala: String
        - capacidade: int
        - getIdSala(): int
        - setIdSala(id: int): boolean
        - getPredio(): String
        - setPredio(predio: String): boolean
        - getSala(): String
        - setSala(sala: String): boolean
        - getCapacidade(): int
        - setCapacidade(capacidade: int): boolean
    }

    class ModeloEquipamento {
        - idModelo: int
        - nome: String
        - marca String
        - getIdModelo(): int
        - setIdModelo(id: int): boolean
        - getNome(): String
        - setNome(nome: String): boolean
        - getMarca(): String
        - setMarca(marca: String): boolean
    }

    ModeloEquipamento <|-- Equipamento
    class Equipamento {
        - idEquipamento: int
        - idModelo: int
        - idSala: int
        - estado: String
        - data_aquisicao: Date
        - getIdEquipamento(): int
        - setIdEquipamento(id: int): boolean
        - getIdModelo(): int
        - setIdModelo(id: int): boolean
        - getIdSala(): int
        - setIdSala(id: int): boolean
        - getDataAquisicao(): Date
        - setDataAquisicao(data: Date): boolean
    }
}

@enduml