@startuml Diagrama de Sequencia

participant Frontend as Frontend
participant "AlunoRoute(route) : IRoutes" as Routes
participant "AlunoController(alunoController) : IAlunoController" as AlunoController
participant "aluno: Aluno" as Aluno
participant "AlunoDAO(alunoDAO) : IAlunoDAO" as AlunoDAO

autonumber 1.1
Frontend->Routes: res = post("api/aluno:cpf", req): Object
AlunoController->AlunoDAO: res = buscarPorCPF(req.params.cpf): Object
AlunoDAO->AlunoController: res
AlunoController->Routes: res
Routes->Frontend: res
Frontend->Routes: res = post("/api/aluno", req) : Object
Routes->AlunoController: res = store(req, body): Object
AlunoController->Aluno: setNome(req.body.nome)
AlunoController->Aluno: setSobrenome(req.body.sobrenome)
AlunoController->Aluno: setCpf(req.body.cpf)
AlunoController->Aluno: setSexo(req.body.sexo)
AlunoController->Aluno: setRaca(req.body.raca)
AlunoController->Aluno: setDataIngresso(req.body.dataIngresso)
AlunoController->Aluno: setDataNascimento(req.body.dataNascimento)
AlunoController->AlunoDAO: res = salvar(aluno): Object
AlunoDAO->AlunoController: res
AlunoController->Routes: res
Routes->Frontend: res
