@startuml Diagrama de Sequencia - Buscar - Oferta

participant Frontend as Frontend
participant "OfertaRoute(route) : IRoutes" as Routes
participant "OfertaController(ofertaController) : IOfertaController" as OfertaController
participant "OfertaDAO(ofertaDAO) : IOfertaDAO" as OfertaDAO

autonumber 1.1
Frontend->Routes: res = get('/api/oferta/', req): List<Oferta>
Routes->OfertaController: res = buscarTodos(): List<Oferta>
OfertaController->OfertaDAO: res = buscarTodos(): List<Oferta>
OfertaDAO->OfertaController: res
OfertaController->Routes: res
Routes->Frontend: res

autonumber inc A
Frontend->Routes: res = get('/api/oferta/{id}', req): Oferta
Routes->OfertaController: res = buscar(req.body.oferta.id_oferta): Oferta
OfertaController->OfertaDAO: res = buscar(id_oferta): Oferta
OfertaDAO->OfertaController: res
OfertaController->Routes: res
Routes->Frontend: res


autonumber inc A
Frontend->Routes: res = get('/api/oferta/nome/{nome}', req): List<Oferta>
Routes->OfertaController: res = buscarPorNome(req.body.oferta.nome): List<Oferta>
OfertaController->OfertaDAO: res = buscarPorNome(nome): List<Oferta>
OfertaDAO->OfertaController: res
OfertaController->Routes: res
Routes->Frontend: res
