@startuml Diagrama de Sequencia

participant Frontend as Frontend
participant "DisciplinaRoute(route) : IRoutes" as Routes
participant "DisciplinaController(disciplinaController) : IDisciplinaController" as DisciplinaController
participant "DisciplinaDAO(disciplinaDAO) : IDisciplinaDAO" as DisciplinaDAO

autonumber 1.1
Frontend->Routes: res = get('/api/disciplina/', req): List<Disciplina>
Routes->DisciplinaController: res = buscarTodos(): List<Disciplina>
DisciplinaController->DisciplinaDAO: res = buscarTodos(): List<Disciplina>
DisciplinaDAO->DisciplinaController: res
DisciplinaController->Routes: res
Routes->Frontend: res

autonumber inc A
Frontend->Routes: res = get('/api/disciplina/{id}', req): Disciplina
Routes->DisciplinaController: res = buscar(req.body.prerequisitos.id): Disciplina
DisciplinaController->DisciplinaDAO: res = buscar(id): Disciplina
DisciplinaDAO->DisciplinaController: res
DisciplinaController->Routes: res
Routes->Frontend: res
