@startuml Diagrama de Sequencia

participant Frontend as Frontend
participant "CursoRoute(route) : IRoutes" as Routes
participant "CursoController(cursoController) : ICursoController" as Controller
participant "curso: Curso" as Curso
participant "CursoDAO(cursoDAO) : ICursoDAO" as DAO

autonumber 1.1
' Verificar se curso existe
Frontend->Routes: res = get("api/curso/{id_curso}", req): Curso
Routes->Controller: res = buscar(req.params.id_curso): Curso
Controller->DAO: res = buscar(id_curso): Curso
DAO->Controller: res
Controller->Routes: res
Routes->Frontend: res

autonumber inc A
' Armazenar curso
Frontend->Routes: res = post("api/curso/", req): Curso
Routes->Controller: res = inserir(req.body): Curso
Controller->Curso: setNome(nome)
Controller->Curso: setCampus(campus)
Controller->DAO: res = inserir(curso): Curso
DAO->Controller: res
Controller->Routes: res
Routes->Frontend: res
